version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
      
  fastapi app:
    build: .
    env_file:
      - ./.env
    command: bash -c "
      uvicorn greens.main:app
      --host 0.0.0.0 --port 8989
      --lifespan=on --use-colors --loop uvloop --http httptools
      --log-config=log-conf.yaml
      --reload
      "
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    depends_on:
      - mongo

volumes:
  mongo:
